#empty so far
server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  messages:
    encoding: UTF-8

provided-back-service:
  url: http://localhost:8081/v2/api  # времянка, адрес пока не известен
